sudo: false
language: cpp

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  fast_finish: true
  include:
    - env: MY_CXX='g++-4.8'
      addons: {apt: { packages: [ g++-4.8 ], sources: *sources }}

    - env: MY_CXX='g++-4.9'
      addons: {apt: { packages: [ g++-4.9 ], sources: *sources }}

    - env: MY_CXX='g++-5'
      addons: {apt: { packages: [ g++-5 ], sources: *sources }}

    - env: MY_CXX='g++-6'
      addons: {apt: { packages: [ g++-6 ], sources: *sources }}

before_install:
  # this is required because Travis exports CC/CXX between `apt addons` and `before_install`
  - export CXX="${MY_CXX}"

script:
  - make
