sudo: false
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - g++-4.9
            - g++-5

env:
    - MY_CXX='g++-4.8'
    - MY_CXX='g++-4.9'
    - MY_CXX='g++-5'

script:
    - make CXX=${MY_CXX}
