sudo: false
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9

env: COMPILER='g++-4.9'

script:
    - make CXX=${COMPILER}
